import { useEffect, useState, type FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase, supabaseConfigured } from '../lib/supabase'
import { getCategories, getProducts, saveProduct } from '../lib/data'
import { defaultSettings, type Category, type Product, type SiteSettings, type Variant } from '../types'

const emptyProduct: Partial<Product> = { title:'',slug:'',excerpt:'',description:'',main_image_url:'',gallery_urls:[],contact_email:'',certifications:'',tags:[],variants:[{model:'',subtitle:'',highlights:['','','',''],specs:[['','']]}],published:true,sort_order:0,category_ids:[] }

export function Admin() {
  const [session,setSession]=useState<Session|null>(null)
  const [loading,setLoading]=useState(true)
  useEffect(()=>{ void supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next)); return ()=>data.subscription.unsubscribe() },[])
  if(!supabaseConfigured) return <AdminShell><div className="admin-notice">Supabase is not configured for this deployment. Add <code>SUPABASE_ANON_KEY</code> as a Cloudflare Worker Variable, then redeploy the Worker.</div></AdminShell>
  if(loading) return <AdminShell><p>Loading…</p></AdminShell>
  if(!session) return <Login/>
  return <Dashboard/>
}

function Login(){ const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); async function submit(e:FormEvent){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message||'')} return <AdminShell><form className="admin-login" onSubmit={submit}><div className="slabel">Vulplink Administration</div><h1>Sign in</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p className="admin-error">{message}</p>}<button className="btn-primary">Sign In</button></form></AdminShell> }

function Dashboard(){
  const [tab,setTab]=useState<'products'|'categories'|'settings'|'enquiries'>('products')
  const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [edit,setEdit]=useState<Partial<Product>|null>(null); const [message,setMessage]=useState('')
  const reload=async()=>{const [p,c]=await Promise.all([getProducts(true),getCategories()]);setProducts(p);setCategories(c)}
  useEffect(()=>{void reload()},[])
  return <AdminShell><div className="admin-top"><div><div className="slabel">Vulplink</div><h1>Content Manager</h1></div><button className="admin-link" onClick={()=>void supabase.auth.signOut()}>Sign Out</button></div><div className="admin-tabs">{(['products','categories','settings','enquiries'] as const).map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div>{message&&<div className="admin-success">{message}</div>}
    {tab==='products'&&<>{edit?<ProductEditor value={edit} categories={categories} onCancel={()=>setEdit(null)} onSaved={async()=>{setEdit(null);setMessage('Product saved.');await reload()}}/>:<><div className="admin-actions"><button className="btn-primary" onClick={()=>setEdit({...emptyProduct})}>+ Add Product</button></div><div className="admin-table">{products.map(product=><div className="admin-row" key={product.id}><div><strong>{product.title}</strong><span>{product.published?'Published':'Draft'} · {product.variants.length} model(s)</span></div><button onClick={()=>setEdit(product)}>Edit</button></div>)}</div></>}</>}
    {tab==='categories'&&<CategoryManager categories={categories} onChanged={reload}/>} {tab==='settings'&&<SettingsManager/>} {tab==='enquiries'&&<Enquiries/>}
  </AdminShell>
}

function ProductEditor({value,categories,onCancel,onSaved}:{value:Partial<Product>;categories:Category[];onCancel:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState(value); const [variantsText,setVariantsText]=useState(JSON.stringify(value.variants||[],null,2)); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const set=(key:keyof Product,val:unknown)=>setForm({...form,[key]:val})
  async function upload(file:File){const path=`products/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await supabase.storage.from('product-images').upload(path,file);if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
  async function mainImage(file?:File){if(!file)return;try{set('main_image_url',await upload(file))}catch(e){setError(e instanceof Error?e.message:'Upload failed')}}
  async function gallery(files:FileList|null){if(!files)return;try{const urls=await Promise.all([...files].map(upload));set('gallery_urls',[...(form.gallery_urls||[]),...urls])}catch(e){setError(e instanceof Error?e.message:'Upload failed')}}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const variants=JSON.parse(variantsText) as Variant[];await saveProduct({...form,slug:form.slug||slugify(form.title||''),tags:typeof form.tags==='string'?(form.tags as unknown as string).split(',').map(s=>s.trim()).filter(Boolean):form.tags,variants});onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setSaving(false)}}
  return <form className="admin-editor" onSubmit={submit}><div className="admin-editor-head"><h2>{form.id?'Edit Product':'Add Product'}</h2><button type="button" onClick={onCancel}>Cancel</button></div><div className="admin-grid"><AdminField label="Product title"><input value={form.title||''} onChange={e=>set('title',e.target.value)} required/></AdminField><AdminField label="URL slug"><input value={form.slug||''} onChange={e=>set('slug',e.target.value)}/></AdminField><AdminField label="Short description" full><textarea value={form.excerpt||''} onChange={e=>set('excerpt',e.target.value)}/></AdminField><AdminField label="Overview (basic HTML supported)" full><textarea rows={7} value={form.description||''} onChange={e=>set('description',e.target.value)}/></AdminField><AdminField label="Main product image"><input type="file" accept="image/*" onChange={e=>void mainImage(e.target.files?.[0])}/>{form.main_image_url&&<img className="admin-thumb" src={form.main_image_url}/>}</AdminField><AdminField label="Gallery images"><input type="file" accept="image/*" multiple onChange={e=>void gallery(e.target.files)}/><div className="admin-thumbs">{form.gallery_urls?.map(url=><img src={url} key={url}/>)}</div></AdminField><AdminField label="Tags (comma separated)" full><input value={(form.tags||[]).join(', ')} onChange={e=>set('tags',e.target.value as unknown as string[])}/></AdminField><AdminField label="Enquiry email"><input type="email" value={form.contact_email||''} onChange={e=>set('contact_email',e.target.value)}/></AdminField><AdminField label="Certifications"><input value={form.certifications||''} onChange={e=>set('certifications',e.target.value)}/></AdminField><AdminField label="Categories" full><div className="admin-checks">{categories.map(category=><label key={category.id}><input type="checkbox" checked={(form.category_ids||[]).includes(category.id)} onChange={e=>set('category_ids',e.target.checked?[...(form.category_ids||[]),category.id]:(form.category_ids||[]).filter(id=>id!==category.id))}/>{category.parent_id?'— ':''}{category.name}</label>)}</div></AdminField><AdminField label="Models / variants (JSON)" full><textarea className="admin-code" rows={16} value={variantsText} onChange={e=>setVariantsText(e.target.value)}/><small>Each model keeps its subtitle, four highlights and ordered specification rows.</small></AdminField><AdminField label="Status"><label><input type="checkbox" checked={form.published??true} onChange={e=>set('published',e.target.checked)}/> Published</label></AdminField></div>{error&&<p className="admin-error">{error}</p>}<button className="btn-primary" disabled={saving}>{saving?'Saving…':'Save Product'}</button></form>
}

function CategoryManager({categories,onChanged}:{categories:Category[];onChanged:()=>Promise<void>}){const [name,setName]=useState('');const [parent,setParent]=useState('');const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();const {error}=await supabase.from('categories').insert({name,slug:slugify(name),parent_id:parent?Number(parent):null});setMessage(error?.message||'Category added.');if(!error){setName('');await onChanged()}}return <div className="admin-card"><h2>Product Categories</h2><form className="admin-inline" onSubmit={submit}><input placeholder="Category name" value={name} onChange={e=>setName(e.target.value)} required/><select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Parent category</option>{categories.filter(c=>!c.parent_id).map(c=><option value={c.id} key={c.id}>Under {c.name}</option>)}</select><button className="btn-primary">Add</button></form>{message&&<p>{message}</p>}<div className="admin-table">{categories.map(c=><div className="admin-row" key={c.id}><div><strong>{c.parent_id?'— ':''}{c.name}</strong><span>/{c.slug}</span></div></div>)}</div></div>}

function SettingsManager(){const [settings,setSettings]=useState<SiteSettings>(defaultSettings);const [message,setMessage]=useState('');useEffect(()=>{void supabase.from('site_settings').select('key,value').then(({data})=>setSettings({...defaultSettings,...Object.fromEntries((data||[]).map(r=>[r.key,r.value]))}))},[]);async function submit(e:FormEvent){e.preventDefault();const rows=Object.entries(settings).map(([key,value])=>({key,value}));const {error}=await supabase.from('site_settings').upsert(rows);setMessage(error?.message||'Site settings saved.')}return <form className="admin-card" onSubmit={submit}><h2>Site Settings</h2>{(['sales_email','sales_phone','support_email','support_phone','address','contact_bg'] as const).map(key=><AdminField label={key.replaceAll('_',' ')} key={key}><input value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></AdminField>)}<AdminField label="Hero slide image URLs"><textarea value={settings.hero_slides.join('\n')} onChange={e=>setSettings({...settings,hero_slides:e.target.value.split('\n').filter(Boolean)})}/></AdminField><AdminField label="About image URLs"><textarea value={settings.about_images.join('\n')} onChange={e=>setSettings({...settings,about_images:e.target.value.split('\n').filter(Boolean)})}/></AdminField>{message&&<p>{message}</p>}<button className="btn-primary">Save Settings</button></form>}

function Enquiries(){const [rows,setRows]=useState<Record<string,unknown>[]>([]);useEffect(()=>{void supabase.from('contact_submissions').select('*').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[]);return <div className="admin-card"><h2>Enquiries</h2><div className="admin-table">{rows.map((row,index)=><div className="admin-row admin-enquiry" key={String(row.id||index)}><div><strong>{String(row.name||'')} · {String(row.kind||'')}</strong><span>{String(row.email||'')} · {new Date(String(row.created_at)).toLocaleString()}</span><p>{String(row.message||'')}</p></div></div>)}</div></div>}
function AdminField({label,children,full}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={`admin-field ${full?'full':''}`}><span>{label}</span>{children}</label>}
function AdminShell({children}:{children:React.ReactNode}){return <main className="admin-shell">{children}</main>}
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
