create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  parent_id bigint references public.categories(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text not null default '',
  description text not null default '',
  main_image_url text not null default '',
  gallery_urls jsonb not null default '[]'::jsonb,
  contact_email text not null default '',
  certifications text not null default '',
  tags jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_categories (
  product_id bigint not null references public.products(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  primary key (product_id, category_id)
);

create table public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('sales','support')),
  name text not null,
  email text not null,
  company text,
  product text,
  order_number text,
  issue_type text,
  message text not null default '',
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_categories enable row level security;
alter table public.site_settings enable row level security;
alter table public.contact_submissions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = auth.uid()) $$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create policy "Published products are public" on public.products for select using (published or public.is_admin());
create policy "Categories are public" on public.categories for select using (true);
create policy "Product category links are public" on public.product_categories for select using (true);
create policy "Site settings are public" on public.site_settings for select using (true);
create policy "Admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage links" on public.product_categories for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage settings" on public.site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins read enquiries" on public.contact_submissions for select using (public.is_admin());

insert into public.site_settings(key,value) values
('sales_email','"sales@vulplink.com"'::jsonb),
('sales_phone','"+1 (800) 000-0000"'::jsonb),
('support_email','"support@vulplink.com"'::jsonb),
('support_phone','"+1 (800) 000-0001"'::jsonb),
('address','"123 Business District, Suite 100"'::jsonb),
('hero_slides','[]'::jsonb),
('about_images','[]'::jsonb),
('contact_bg','""'::jsonb);

insert into storage.buckets(id,name,public) values ('product-images','product-images',true) on conflict (id) do nothing;
create policy "Public product images" on storage.objects for select using (bucket_id='product-images');
create policy "Admins upload product images" on storage.objects for insert with check (bucket_id='product-images' and public.is_admin());
create policy "Admins update product images" on storage.objects for update using (bucket_id='product-images' and public.is_admin());
create policy "Admins delete product images" on storage.objects for delete using (bucket_id='product-images' and public.is_admin());

-- After creating your first Auth user, run:
-- insert into public.admin_users(user_id) values ('YOUR-AUTH-USER-UUID');
